apiVersion: v1
kind: Service
metadata:
  name: __RELEASE_NAME__
  namespace: __NAMESPACE__
  labels:
    app.kubernetes.io/name: ether-chat-backend
    app.kubernetes.io/instance: __RELEASE_NAME__
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ether-chat-backend
    app.kubernetes.io/instance: __RELEASE_NAME__
  ports:
    - name: http
      port: 80
      targetPort: 8080
